### ISSUE TITLE
Response not being received

### ISSUE THREAD

**Issue by stevejoung** [elektor-labs/ChatGPTxESP32#6]
Everything is working now except the ESP32_1 is not receiving the response from ESP32_2.  ESP32_2 is printng the response it is not seen by ESP32_1. I have tried extending the delay in line 85 to 10000 but still no response received.

**Comment by Saad-Imtiaz** [comment]
Hey @stevejoung, 
In the code, this could be happening because the client (ESP32_1) may have closed the connection before this line of code executes. This can happen if the client doesn't wait for the response after sending the code snippet. Ensure the client maintains the connection open until it receives the response.

You can resolve this issue by keeping the connection open from the client side with this code : 

```
else if (input == "SEND" || input == "MYCODE") {
    if (client.connect(serverIP, serverPort)) {
        String sendCode = (input == "SEND") ? response : Serial.readStringUntil('\n');
        sendCode.trim();
        Serial.println(sendCode);
        
        // Ensure the message ends with a newline character to signal the end of transmission
        client.println(sendCode + "\n"); // Append a newline character
        Serial.println("Code sent to server");

        // Wait for a response or timeout after a period
        unsigned long startTime = millis();
        while (client.connected() && millis() - startTime < 5000) { // 5-second timeout
            if (client.available()) {
                String serverResponse = client.readStringUntil('\n');
                Serial.println("Server response: " + serverResponse);
                break; // Exit loop once a response is received
            }
        }
        if (!client.available()) {
            Serial.println("No response received or connection timed out.");
        }
        client.stop();
        Serial.println("Connection closed");
    }
    else {
        Serial.println("Connection failed");
    }
    blinkLed();
}
```

**Comment by stevejoung** [comment]
Thanks for the reply. Unfortunately, using your code, the monitor on the client (ESP32_1) reads:
```
Code sent to server
No response received or connection timed out.
Connection closed
```
I am guessing that this means the problem is in the MicoPython script?

**Comment by stevejoung** [comment]
Still have this problem, the ESP_1 doesn't receive a response from the ESP_2 line "client.sendall(response.encode())"

I have tried all I can think of with both scripts but cannot get the response. Everthing else is fine.

**Comment by stevejoung** [comment]
I have been in contact with the Arduino Forum about this and an Arduino employee tells me that this will never finish until it receives 1024 bytes of data, and the second part of the problem is that if your code is longer it will be executed "wrong" and break.

```
while True:
  data = client.recv(1024)
  print(f'data: {data}')
  if not data:
    break
  code += data.decode()
```

**Comment by Saad-Imtiaz** [comment]
Can you try with something simple, like printing out a "hello world" instead of the running the code, start with that, and then we can solve what is the main issue?

**Comment by stevejoung** [comment]
I have commented out the whole try block and replaced it with 

```
# Execute the received code
    print ("trying code")
    client.sendall("trying code".encode())
```

The result on the MP NanoESP32 is :

> Client connected: ('192.168.178.58', 51353)
> trying code
> Client disconnected
> Waiting for connection...

And on the C NanoESP32 is :

> Code sent to server
> No response received or connection timed out.
> Connection closed
